### ISSUE TITLE
sdc-docker-setup.sh script does not work on OS X 10.10

### ISSUE THREAD

**Issue by hairyhenderson** [joyent/sdc-docker#39] opened 2015-06-18 02:05 UTC
```console
$ sh sdc-docker-setup.sh https://us-east-1.api.joyentcloud.com myuser ~/.ssh/id_rsa 
Setting up Docker client for SDC using:
    CloudAPI:        https://us-east-1.api.joyentcloud.com
    Account:         myuser
    Key:             /Users/epoch/.ssh/id_rsa

$ echo $?
1
```

Digging into the script, it looks like the `sshGetMD5Fingerprint` function is at fault, specifically this command:

```sh
    s=$(ssh-keygen -E md5 -l -f "$sshPubKeyPath" 2> /dev/null)
```

The version of ssh-keygen that I have on my Mac doesn't have a `-E` option.

```console
$ ssh -V
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
```

Based on the comment above the `sshGetMD5Fingerprint` function, it looks like this was written assuming OpenSSH 6.8 or above. This is going to be a problem for other OS X users with the default SSH client...

**Comment by lloydde** [comment] 2015-06-18 04:15
@hairyhenderson there is a fallback for older OpenSSH right under that in the script: https://github.com/joyent/sdc-docker/blob/master/tools/sdc-docker-setup.sh#L121

~~~
    s=$(ssh-keygen -E md5 -l -f "$sshPubKeyPath" 2> /dev/null)
    if [[ $? -eq  0 ]]; then
        echo "$s" | awk '{print $2}' | tr -d '\n' | cut -d: -f2-;
    else
        # OpenSSH version < 6.8
        ssh-keygen -l -f "$sshPubKeyPath" | awk '{print $2}' | tr -d '\n';
    fi
~~~

**Comment by lloydde** [comment] 2015-06-18 04:23
hmm, I am also able to reproduce the failure now though.

**Comment by lloydde** [comment] 2015-06-18 04:31
@hairyhenderson could you test with `bash sdc-docker-setup.sh` instead of `sh sdc-docker-setup.sh`?

**Comment by lloydde** [comment] 2015-06-18 04:34
Fun, "If bash is invoked with the name sh, it tries to mimic the startup behavior of historical versions of sh as closely as possible, while conforming to the POSIX standard as well."

**Comment by hairyhenderson** [comment] 2015-06-18 11:25
@lloydde - ah, sneaky... `bash` works. I see you've got a commit to fix this so I'll leave this open until that gets merged. Thank you!

**Comment by rmustacc** [comment] 2015-06-18 15:38
@hairyhenderson were there instructions that indicated that you should use sh? If so, we should get them fixed, as the script is unlikely to turn into a proper sh script anytime soon. sh almost works by fluke on OS X because sh is a link to bash and bash isn't that strict with sh compat.

**Comment by ryanpuck** [comment] 2015-06-18 15:42
It states to use sh at https://apidocs.joyent.com/docker/

**Comment by lloydde** [comment] 2015-06-18 15:53
Also in the blog posts, I'll make those changes now.

**Comment by trentm** [comment] 2015-06-18 16:13
@lloydde thanks!

**Comment by lloydde** [comment] 2015-06-18 22:58
Jira ticket: https://smartos.org/bugview/DOCKER-442.

**Comment by andrew-wharton** [comment] 2015-06-19 03:33
please also fix https://my.joyent.com/main/#!/docker/intro, stopped me in my tracks... :-(

**Comment by lloydde** [comment] 2015-06-19 04:52
@andrew-wharton sorry about that, I have a pull request for that joyent/piranha#3218 and the team lead, @dan-luk hopes to get it merged and hopefully online tomorrow.
/cc @eviking , @tysonhom .

**Comment by lloydde** [comment] 2015-06-19 22:00
sdc-docker-setup.sh will now complain and give correct command to run, joyent/sdc-docker@0d9733db6e0a96b0af3b97e41098541f7d608b92 . Thanks @trentm !

Keeping open pending JPC portal fix deployed.

**Comment by xer0x** [comment] 2016-01-06 23:55
Closing. This has been deployed to the JPC portal.

**Closed by xer0x** 2016-01-06 23:55 UTC
